### ISSUE TITLE
empty parentheses

### ISSUE THREAD

**Issue by Johnicholas** [nuex/zodiac#4]
On my system I get:

$ find "site" -type f \( \) -exec zod-render "/usr/local/lib/zodiac" "site" "www" {} \;
find: invalid expression; empty parentheses are not allowed.

I don't really understand what the parentheses are supposed to contain - according to Posix a parenthesized expression is true if the expression inside is true?

**Comment by Johnicholas** [comment]
possibly I caused this bug by editing the source to try to get rid of uses of length(array); sorry.

**Comment by nuex** [comment]
No problem! Feel free to open a pull request!
